// 1000 most common Italian words with Spanish translations
// Format: [italian, spanish, phonetic, example_it, category]
const WORDS_1000 = [
// ── VERBS ──────────────────────────────────────────────────────
["essere","ser / estar","ES-se-re","Io sono stanco.","Verbi"],
["avere","tener / haber","a-VE-re","Ho fame.","Verbi"],
["fare","hacer","FA-re","Cosa fai?","Verbi"],
["dire","decir","DI-re","Cosa vuoi dire?","Verbi"],
["potere","poder","po-TE-re","Non posso venire.","Verbi"],
["andare","ir","an-DA-re","Vado a casa.","Verbi"],
["sapere","saber","sa-PE-re","Non so niente.","Verbi"],
["dare","dar","DA-re","Dammi un attimo.","Verbi"],
["stare","estar / quedarse","STA-re","Come stai?","Verbi"],
["venire","venir","ve-NI-re","Vieni con me?","Verbi"],
["volere","querer","vo-LE-re","Voglio un caffè.","Verbi"],
["vedere","ver","ve-DE-re","Vedo il mare.","Verbi"],
["dovere","deber","do-VE-re","Devo andare.","Verbi"],
["pensare","pensar","pen-SA-re","Penso di sì.","Verbi"],
["parlare","hablar","par-LA-re","Parlo italiano.","Verbi"],
["trovare","encontrar","tro-VA-re","Ho trovato le chiavi.","Verbi"],
["lasciare","dejar","la-SHA-re","Lascia stare.","Verbi"],
["sembrare","parecer","sem-BRA-re","Sembra difficile.","Verbi"],
["sentire","sentir","sen-TI-re","Sento musica.","Verbi"],
["tenere","tener","te-NE-re","Tieni il mio posto.","Verbi"],
["portare","llevar / traer","por-TA-re","Porto il pranzo.","Verbi"],
["chiedere","pedir / preguntar","KJE-de-re","Posso chiederti qualcosa?","Verbi"],
["conoscere","conocer","ko-NO-she-re","Conosco Roma.","Verbi"],
["vivere","vivir","VI-ve-re","Vivo a Milano.","Verbi"],
["cercare","buscar","cher-KA-re","Cerco lavoro.","Verbi"],
["prendere","tomar / coger","PREN-de-re","Prendo il treno.","Verbi"],
["mettere","poner","MET-te-re","Metti qui.","Verbi"],
["partire","partir / salir","par-TI-re","Parto domani.","Verbi"],
["tornare","volver","tor-NA-re","Torno a casa.","Verbi"],
["capire","entender","ka-PI-re","Non capisco.","Verbi"],
["cominciare","comenzar / empezar","ko-min-CHA-re","Cominciamo!","Verbi"],
["finire","terminar / acabar","fi-NI-re","Ho finito.","Verbi"],
["leggere","leer","LED-je-re","Leggo ogni giorno.","Verbi"],
["scrivere","escribir","SKRI-ve-re","Ti scrivo dopo.","Verbi"],
["mangiare","comer","man-JA-re","Mangiamo insieme.","Verbi"],
["bere","beber","BE-re","Bevo acqua.","Verbi"],
["dormire","dormir","dor-MI-re","Dormo poco.","Verbi"],
["lavorare","trabajar","la-vo-RA-re","Lavoro molto.","Verbi"],
["aspettare","esperar","as-pet-TA-re","Aspetta un momento.","Verbi"],
["chiamare","llamar","kja-MA-re","Mi chiamo Daniel.","Verbi"],
["aprire","abrir","a-PRI-re","Apri la finestra.","Verbi"],
["chiudere","cerrar","KJU-de-re","Chiudi la porta.","Verbi"],
["perdere","perder","PER-de-re","Ho perso le chiavi.","Verbi"],
["cambiare","cambiar","kam-BJA-re","Vuoi cambiare?","Verbi"],
["usare","usar / utilizar","u-ZA-re","Uso il telefono.","Verbi"],
["rispondere","responder","ris-PON-de-re","Rispondi subito.","Verbi"],
["diventare","convertirse / volverse","di-ven-TA-re","È diventato grande.","Verbi"],
["ricordare","recordar","ri-kor-DA-re","Ricordo tutto.","Verbi"],
["scegliere","elegir / escoger","SHE-lje-re","Scegli tu.","Verbi"],
["aiutare","ayudar","a-ju-TA-re","Puoi aiutarmi?","Verbi"],
["credere","creer","KRE-de-re","Ci credo.","Verbi"],
["giocare","jugar","jo-KA-re","Giochiamo a calcio.","Verbi"],
["passare","pasar","pas-SA-re","Passa da me.","Verbi"],
["spiegare","explicar","spje-GA-re","Puoi spiegare?","Verbi"],
["mostrare","mostrar","mos-TRA-re","Mostrami la foto.","Verbi"],
["pagare","pagar","pa-GA-re","Pago io.","Verbi"],
["comprare","comprar","kom-PRA-re","Compro pane.","Verbi"],
["vendere","vender","VEN-de-re","Vendo la macchina.","Verbi"],
["ricevere","recibir","ri-CHE-ve-re","Ho ricevuto il pacco.","Verbi"],
["imparare","aprender","im-pa-RA-re","Imparo l'italiano.","Verbi"],
["cadere","caer","ka-DE-re","È caduto.","Verbi"],
["correre","correr","KOR-re-re","Corro ogni mattina.","Verbi"],
["camminare","caminar / andar","kam-mi-NA-re","Cammino molto.","Verbi"],
["alzarsi","levantarse","al-ZAR-si","Mi alzo presto.","Verbi"],
["sedersi","sentarse","se-DER-si","Siediti qui.","Verbi"],
["guardare","mirar / ver","gwar-DA-re","Guarda là!","Verbi"],
["ascoltare","escuchar","as-kol-TA-re","Ascolta bene.","Verbi"],
["toccare","tocar","tok-KA-re","Non toccare.","Verbi"],
["uscire","salir","u-SHI-re","Esco alle 8.","Verbi"],
["entrare","entrar","en-TRA-re","Entra pure.","Verbi"],
["spendere","gastar","SPEN-de-re","Spendo poco.","Verbi"],
["mandare","mandar / enviar","man-DA-re","Mandami un messaggio.","Verbi"],
["succedere","suceder / pasar","suc-CHE-de-re","Cosa è successo?","Verbi"],
["accadere","ocurrir / suceder","ak-ka-DE-re","Cosa è accaduto?","Verbi"],
["nascere","nacer","NA-she-re","Sono nato a Roma.","Verbi"],
["morire","morir","mo-RI-re","È morto ieri.","Verbi"],
["costruire","construir","kos-TRU-i-re","Costruiscono una casa.","Verbi"],
["sognare","soñar","son-JA-re","Sogno di viaggiare.","Verbi"],
["ridere","reír","RI-de-re","Mi fa ridere.","Verbi"],
["piangere","llorar","PJAN-je-re","Non piangere.","Verbi"],
["amare","amar / querer","a-MA-re","Ti amo.","Verbi"],
["odiare","odiar","o-DJA-re","Odio il traffico.","Verbi"],
["preferire","preferir","pre-fe-RI-re","Preferisco il vino.","Verbi"],
["sperare","esperar","spe-RA-re","Spero di sì.","Verbi"],
["decidere","decidir","de-CHI-de-re","Ho deciso.","Verbi"],
["permettere","permitir","per-MET-te-re","Permettimi di spiegare.","Verbi"],
["continuare","continuar","kon-ti-NWA-re","Continua così.","Verbi"],
["smettere","dejar de / parar","ZMET-te-re","Smettila!","Verbi"],
["offrire","ofrecer","of-FRI-re","Offro io.","Verbi"],
["aggiungere","añadir / agregar","ad-JUN-je-re","Aggiungi il sale.","Verbi"],
["seguire","seguir","se-GWI-re","Seguimi.","Verbi"],
["avvicinarsi","acercarse","av-vi-chi-NAR-si","Si è avvicinato.","Verbi"],
["dimenticare","olvidar","di-men-ti-KA-re","Ho dimenticato.","Verbi"],
["presentare","presentar","pre-zen-TA-re","Ti presento Marco.","Verbi"],
["preparare","preparar","pre-pa-RA-re","Preparo la cena.","Verbi"],
["cucinare","cocinar","ku-chi-NA-re","Sa cucinare bene.","Verbi"],
["pulire","limpiar","pu-LI-re","Pulisco la casa.","Verbi"],
["riuscire","lograr / conseguir","riu-SHI-re","Ce la faccio.","Verbi"],
["dimostrare","demostrar","di-mos-TRA-re","Lo dimostrerò.","Verbi"],
["provare","intentar / probar","pro-VA-re","Proviamo!","Verbi"],
["sognare","soñar","son-JA-re","Ho sognato te.","Verbi"],
["incontrare","encontrar / quedar","in-kon-TRA-re","L'ho incontrata ieri.","Verbi"],
// ── NOUNS ──────────────────────────────────────────────────────
["anno","año","AN-no","Quest'anno è difficile.","Sostantivi"],
["giorno","día","JOR-no","Buon giorno!","Sostantivi"],
["uomo","hombre","WO-mo","È un uomo gentile.","Sostantivi"],
["donna","mujer","DON-na","Una donna coraggiosa.","Sostantivi"],
["bambino","niño","bam-BI-no","Il bambino ride.","Sostantivi"],
["tempo","tiempo / vez","TEM-po","Che tempo fa?","Sostantivi"],
["cosa","cosa","KO-za","Che cosa vuoi?","Sostantivi"],
["casa","casa","KA-za","Vado a casa.","Sostantivi"],
["modo","modo / manera","MO-do","In che modo?","Sostantivi"],
["vita","vida","VI-ta","La vita è bella.","Sostantivi"],
["mano","mano","MA-no","Dammi la mano.","Sostantivi"],
["parte","parte","PAR-te","Fai parte del gruppo.","Sostantivi"],
["occhio","ojo","OK-kjo","Ha gli occhi verdi.","Sostantivi"],
["volta","vez","VOL-ta","Un'altra volta.","Sostantivi"],
["fatto","hecho","FAT-to","Questo è un fatto.","Sostantivi"],
["paese","país / pueblo","pa-E-ze","Il mio paese natale.","Sostantivi"],
["città","ciudad","chit-TA","Roma è una bella città.","Sostantivi"],
["mondo","mundo","MON-do","In tutto il mondo.","Sostantivi"],
["ragazzo","chico / joven","ra-GAT-tso","Il ragazzo studia.","Sostantivi"],
["ragazza","chica / joven","ra-GAT-tsa","Una ragazza simpatica.","Sostantivi"],
["lavoro","trabajo","la-VO-ro","Ho trovato lavoro.","Sostantivi"],
["problema","problema","pro-BLE-ma","Non c'è problema.","Sostantivi"],
["momento","momento","mo-MEN-to","Un momento!","Sostantivi"],
["posto","lugar / sitio","POS-to","Che bel posto!","Sostantivi"],
["gente","gente","JEN-te","La gente è gentile.","Sostantivi"],
["sera","tarde / noche","SE-ra","Buona sera!","Sostantivi"],
["padre","padre","PA-dre","Mio padre lavora.","Sostantivi"],
["madre","madre","MA-dre","Mia madre cucina.","Sostantivi"],
["figlio","hijo","FI-ljo","Ho un figlio.","Sostantivi"],
["figlia","hija","FI-lja","La sua figlia studia.","Sostantivi"],
["amico","amigo","a-MI-ko","Il mio amico Marco.","Sostantivi"],
["parola","palabra","pa-RO-la","Non trovavo le parole.","Sostantivi"],
["punto","punto","PUN-to","Hai ragione su quel punto.","Sostantivi"],
["notte","noche","NOT-te","Buona notte!","Sostantivi"],
["mattina","mañana","mat-TI-na","Di mattina bevo caffè.","Sostantivi"],
["numero","número","NU-me-ro","Qual è il numero?","Sostantivi"],
["testa","cabeza","TES-ta","Ho mal di testa.","Sostantivi"],
["storia","historia / historia","STO-rja","Una bella storia.","Sostantivi"],
["idea","idea","i-DE-a","Buona idea!","Sostantivi"],
["ore","horas","O-re","Sono le tre.","Sostantivi"],
["voce","voz","VO-che","Ha una bella voce.","Sostantivi"],
["corpo","cuerpo","KOR-po","Il corpo umano.","Sostantivi"],
["terra","tierra","TER-ra","La terra è tonda.","Sostantivi"],
["aria","aire","A-rja","L'aria è fresca.","Sostantivi"],
["acqua","agua","AK-kwa","Un po' d'acqua.","Sostantivi"],
["fuoco","fuego","FWO-ko","Il fuoco brucia.","Sostantivi"],
["luce","luz","LU-che","La luce del sole.","Sostantivi"],
["colore","color","ko-LO-re","Che colore preferisci?","Sostantivi"],
["nome","nombre","NO-me","Come ti chiami?","Sostantivi"],
["libro","libro","LI-bro","Leggo un libro.","Sostantivi"],
["porta","puerta","POR-ta","Apri la porta.","Sostantivi"],
["finestra","ventana","fi-NES-tra","Guarda dalla finestra.","Sostantivi"],
["strada","calle / carretera","STRA-da","La strada è lunga.","Sostantivi"],
["macchina","coche / carro","MAK-ki-na","Ho la macchina.","Sostantivi"],
["treno","tren","TRE-no","Prendo il treno.","Sostantivi"],
["aereo","avión","a-E-re-o","L'aereo parte alle 8.","Sostantivi"],
["scuola","escuela","SKWO-la","Vado a scuola.","Sostantivi"],
["università","universidad","u-ni-ver-si-TA","Studio all'università.","Sostantivi"],
["ufficio","oficina","uf-FI-cho","Sono in ufficio.","Sostantivi"],
["ospedale","hospital","os-pe-DA-le","Vado all'ospedale.","Sostantivi"],
["ristorante","restaurante","ris-to-RAN-te","Ceniamo al ristorante.","Sostantivi"],
["negozio","tienda","ne-GO-tsjo","Vado al negozio.","Sostantivi"],
["mercato","mercado","mer-KA-to","Al mercato stamattina.","Sostantivi"],
["supermercato","supermercado","su-per-mer-KA-to","Vado al supermercato.","Sostantivi"],
["soldi","dinero","SOL-di","Non ho soldi.","Sostantivi"],
["prezzo","precio","PRET-tso","Il prezzo è alto.","Sostantivi"],
["cibo","comida / alimento","CHI-bo","Il cibo italiano è buono.","Sostantivi"],
["pane","pan","PA-ne","Un pezzo di pane.","Sostantivi"],
["vino","vino","VI-no","Un bicchiere di vino.","Sostantivi"],
["caffè","café","kaf-FÈ","Un caffè, per favore.","Sostantivi"],
["birra","cerveza","BIR-ra","Una birra fresca.","Sostantivi"],
["carne","carne","KAR-ne","Mangio poca carne.","Sostantivi"],
["pesce","pescado / pez","PE-she","Il pesce è fresco.","Sostantivi"],
["frutta","fruta","FRUT-ta","Mangio frutta ogni giorno.","Sostantivi"],
["verdura","verdura / verduras","ver-DU-ra","Le verdure fanno bene.","Sostantivi"],
["telefono","teléfono","te-LE-fo-no","Il mio telefono suona.","Sostantivi"],
["computer","computadora / ordenador","kom-PJU-ter","Lavoro al computer.","Sostantivi"],
["internet","internet","in-ter-NET","Connessione internet lenta.","Sostantivi"],
["messaggio","mensaje","mes-SAD-jo","Ti mando un messaggio.","Sostantivi"],
["foto","foto","FO-to","Una bella foto.","Sostantivi"],
["musica","música","MU-zi-ka","Ascolto musica.","Sostantivi"],
["film","película","FILM","Ho visto un bel film.","Sostantivi"],
["sport","deporte","SPORT","Faccio sport.","Sostantivi"],
["calcio","fútbol","KAL-cho","Il calcio è popolare.","Sostantivi"],
["viaggio","viaje","VJAD-jo","Buon viaggio!","Sostantivi"],
["vacanza","vacaciones","va-KAN-tsa","Le vacanze estive.","Sostantivi"],
["famiglia","familia","fa-MI-lja","La mia famiglia.","Sostantivi"],
["marito","marido / esposo","ma-RI-to","Mio marito lavora.","Sostantivi"],
["moglie","esposa / mujer","MO-lje","Mia moglie cucina.","Sostantivi"],
["fratello","hermano","fra-TEL-lo","Ho un fratello.","Sostantivi"],
["sorella","hermana","so-REL-la","Mia sorella studia.","Sostantivi"],
["nonno","abuelo","NON-no","Mio nonno ha 80 anni.","Sostantivi"],
["nonna","abuela","NON-na","La nonna cucina bene.","Sostantivi"],
["nipote","nieto / sobrino","ni-PO-te","Il mio nipote.","Sostantivi"],
["zio","tío","TSIO","Mio zio è simpatico.","Sostantivi"],
["zia","tía","TSIA","Mia zia abita a Roma.","Sostantivi"],
["cuore","corazón","KWO-re","Con tutto il cuore.","Sostantivi"],
["mente","mente","MEN-te","Cambia idea di mente.","Sostantivi"],
["sogno","sueño","SON-jo","Ho un sogno.","Sostantivi"],
["paura","miedo","pa-U-ra","Ho paura.","Sostantivi"],
["amore","amor","a-MO-re","È amore.","Sostantivi"],
["felicità","felicidad","fe-li-chi-TA","La felicità è importante.","Sostantivi"],
["libertà","libertad","li-ber-TA","Viva la libertà.","Sostantivi"],
["pace","paz","PA-che","Voglio la pace.","Sostantivi"],
["guerra","guerra","GWER-ra","La guerra è terribile.","Sostantivi"],
["salute","salud","sa-LU-te","Salute! (toast)","Sostantivi"],
["malattia","enfermedad","ma-lat-TI-a","Una malattia grave.","Sostantivi"],
["medicina","medicina","me-di-CHI-na","Prendo la medicina.","Sostantivi"],
["dottore","médico / doctor","dot-TO-re","Vado dal dottore.","Sostantivi"],
["ambiente","ambiente / medio ambiente","am-BJEN-te","Rispetta l'ambiente.","Sostantivi"],
["natura","naturaleza","na-TU-ra","La natura è bella.","Sostantivi"],
["mare","mar","MA-re","Vado al mare.","Sostantivi"],
["montagna","montaña","mon-TAN-ja","In montagna fa freddo.","Sostantivi"],
["fiume","río","FJU-me","Il fiume Po.","Sostantivi"],
["cielo","cielo","CHE-lo","Il cielo è blu.","Sostantivi"],
["sole","sol","SO-le","Oggi c'è il sole.","Sostantivi"],
["luna","luna","LU-na","La luna è piena.","Sostantivi"],
["stella","estrella","STEL-la","Una stella luminosa.","Sostantivi"],
["pioggia","lluvia","PJOD-ja","Fuori piove.","Sostantivi"],
["neve","nieve","NE-ve","La neve è bianca.","Sostantivi"],
["vento","viento","VEN-to","Fa vento oggi.","Sostantivi"],
["inverno","invierno","in-VER-no","L'inverno è freddo.","Sostantivi"],
["estate","verano","es-TA-te","D'estate fa caldo.","Sostantivi"],
["primavera","primavera","pri-ma-VE-ra","Mi piace la primavera.","Sostantivi"],
["autunno","otoño","a-TUN-no","L'autunno è bello.","Sostantivi"],
["settimana","semana","set-ti-MA-na","La settimana prossima.","Sostantivi"],
["mese","mes","ME-ze","Questo mese.","Sostantivi"],
["lunedì","lunes","lu-ne-DI","Lunedì vado al lavoro.","Sostantivi"],
["martedì","martes","mar-te-DI","Ci vediamo martedì.","Sostantivi"],
["mercoledì","miércoles","mer-ko-le-DI","È mercoledì.","Sostantivi"],
["giovedì","jueves","jo-ve-DI","Giovedì sera usciamo.","Sostantivi"],
["venerdì","viernes","ve-ner-DI","Venerdì è l'ultimo giorno.","Sostantivi"],
["sabato","sábado","SA-ba-to","Sabato riposo.","Sostantivi"],
["domenica","domingo","do-ME-ni-ka","La domenica vado a messa.","Sostantivi"],
["gennaio","enero","jen-NA-jo","A gennaio fa freddo.","Sostantivi"],
["febbraio","febrero","feb-BRA-jo","Febbraio è corto.","Sostantivi"],
["marzo","marzo","MAR-tso","A marzo arriva la primavera.","Sostantivi"],
["aprile","abril","a-PRI-le","Aprile dolce dormire.","Sostantivi"],
["maggio","mayo","MAD-jo","A maggio fa bello.","Sostantivi"],
["giugno","junio","JUN-jo","In giugno inizia l'estate.","Sostantivi"],
["luglio","julio","LUL-jo","A luglio vado in vacanza.","Sostantivi"],
["agosto","agosto","a-GOS-to","Ad agosto c'è il caldo.","Sostantivi"],
["settembre","septiembre","set-TEM-bre","A settembre ricomincia la scuola.","Sostantivi"],
["ottobre","octubre","ot-TO-bre","In ottobre le foglie cadono.","Sostantivi"],
["novembre","noviembre","no-VEM-bre","A novembre piove.","Sostantivi"],
["dicembre","diciembre","di-CHEM-bre","A dicembre Natale.","Sostantivi"],
// ── ADJECTIVES ────────────────────────────────────────────────
["buono","bueno","BWO-no","Il cibo è buono.","Aggettivi"],
["cattivo","malo","kat-TI-vo","Tempo cattivo.","Aggettivi"],
["bello","bonito / hermoso","BEL-lo","Che bel paesaggio!","Aggettivi"],
["brutto","feo / horrible","BRUT-to","Che brutta giornata.","Aggettivi"],
["grande","grande","GRAN-de","Una città grande.","Aggettivi"],
["piccolo","pequeño","PIK-ko-lo","Un appartamento piccolo.","Aggettivi"],
["lungo","largo","LUN-go","Una strada lunga.","Aggettivi"],
["corto","corto","KOR-to","Capelli corti.","Aggettivi"],
["alto","alto","AL-to","Un palazzo alto.","Aggettivi"],
["basso","bajo","BAS-so","Una voce bassa.","Aggettivi"],
["nuovo","nuevo","NWO-vo","Una macchina nuova.","Aggettivi"],
["vecchio","viejo","VEK-kjo","Un palazzo vecchio.","Aggettivi"],
["giovane","joven","JO-va-ne","È ancora giovane.","Aggettivi"],
["importante","importante","im-por-TAN-te","È importante.","Aggettivi"],
["possibile","posible","pos-SI-bi-le","È possibile.","Aggettivi"],
["impossibile","imposible","im-pos-SI-bi-le","È impossibile.","Aggettivi"],
["facile","fácil","FA-chi-le","È facile.","Aggettivi"],
["difficile","difícil","dif-FI-chi-le","È difficile.","Aggettivi"],
["vero","verdadero / cierto","VE-ro","È vero.","Aggettivi"],
["falso","falso","FAL-so","È falso.","Aggettivi"],
["giusto","correcto / justo","JUS-to","Non è giusto.","Aggettivi"],
["sbagliato","equivocado / erróneo","zbal-JA-to","Ho sbagliato strada.","Aggettivi"],
["pronto","listo / preparado","PRON-to","Sei pronto?","Aggettivi"],
["libero","libre","LI-be-ro","Sei libero stasera?","Aggettivi"],
["occupato","ocupado","ok-ku-PA-to","Sono occupato.","Aggettivi"],
["stanco","cansado","STAN-ko","Sono stanco.","Aggettivi"],
["felice","feliz","fe-LI-che","Sono felice.","Aggettivi"],
["triste","triste","TRIS-te","Mi sento triste.","Aggettivi"],
["arrabbiato","enojado / enfadado","ar-rab-BJA-to","È arrabbiato.","Aggettivi"],
["contento","contento / satisfecho","kon-TEN-to","Sono contento.","Aggettivi"],
["tranquillo","tranquilo / calmado","tran-KWIL-lo","Stai tranquillo.","Aggettivi"],
["nervoso","nervioso","ner-VO-zo","Sono nervoso.","Aggettivi"],
["sicuro","seguro","si-KU-ro","Sei sicuro?","Aggettivi"],
["certo","cierto / seguro","CHER-to","Certamente!","Aggettivi"],
["uguale","igual","u-GWA-le","È uguale.","Aggettivi"],
["diverso","diferente / distinto","di-VER-so","Sono diversi.","Aggettivi"],
["stesso","mismo","STES-so","È la stessa cosa.","Aggettivi"],
["solo","solo / único","SO-lo","Sono solo.","Aggettivi"],
["insieme","juntos","in-SJE-me","Stiamo insieme.","Aggettivi"],
["caro","caro / querido","KA-ro","È troppo caro.","Aggettivi"],
["economico","económico / barato","e-ko-NO-mi-ko","È economico.","Aggettivi"],
["pieno","lleno","PJE-no","Il bicchiere è pieno.","Aggettivi"],
["vuoto","vacío","VWO-to","Il bicchiere è vuoto.","Aggettivi"],
["aperto","abierto","a-PER-to","Il negozio è aperto.","Aggettivi"],
["chiuso","cerrado","KJU-zo","È chiuso.","Aggettivi"],
["forte","fuerte","FOR-te","È una persona forte.","Aggettivi"],
["debole","débil","DE-bo-le","Mi sento debole.","Aggettivi"],
["veloce","rápido / veloz","ve-LO-che","Sei veloce.","Aggettivi"],
["lento","lento","LEN-to","Il servizio è lento.","Aggettivi"],
["freddo","frío","FRED-do","Ho freddo.","Aggettivi"],
["caldo","caliente / caluroso","KAL-do","Ho caldo.","Aggettivi"],
["fresco","fresco","FRES-ko","Fa fresco oggi.","Aggettivi"],
["pulito","limpio","pu-LI-to","La casa è pulita.","Aggettivi"],
["sporco","sucio","SPOR-ko","È sporco.","Aggettivi"],
["sano","sano / saludable","SA-no","Mangiare sano.","Aggettivi"],
["malato","enfermo","ma-LA-to","Sono malato.","Aggettivi"],
["intero","entero","in-TE-ro","L'intera giornata.","Aggettivi"],
["prossimo","próximo / siguiente","PROS-si-mo","La settimana prossima.","Aggettivi"],
["ultimo","último","UL-ti-mo","L'ultima volta.","Aggettivi"],
["primo","primero","PRI-mo","Il primo giorno.","Aggettivi"],
["secondo","segundo","se-KON-do","Il secondo piano.","Aggettivi"],
["migliore","mejor","mi-LJO-re","È il migliore.","Aggettivi"],
["peggiore","peor","ped-JO-re","È il peggiore.","Aggettivi"],
["troppo","demasiado","TROP-po","È troppo.","Aggettivi"],
["abbastanza","bastante / suficiente","ab-bas-TAN-tsa","È abbastanza.","Aggettivi"],
["simpatico","simpático / agradable","sim-PA-ti-ko","È molto simpatico.","Aggettivi"],
["antipatico","antipático","an-ti-PA-ti-ko","È antipatico.","Aggettivi"],
["gentile","amable / gentil","jen-TI-le","Sei gentile.","Aggettivi"],
["intelligente","inteligente","in-tel-li-JEN-te","È intelligente.","Aggettivi"],
["stupido","estúpido / tonto","STU-pi-do","Non essere stupido.","Aggettivi"],
["ricco","rico","RIK-ko","È molto ricco.","Aggettivi"],
["povero","pobre","PO-ve-ro","È molto povero.","Aggettivi"],
["famoso","famoso / célebre","fa-MO-zo","È famoso.","Aggettivi"],
["normale","normal","nor-MA-le","È normale.","Aggettivi"],
["strano","extraño / raro","STRA-no","Che strano!","Aggettivi"],
["interessante","interesante","in-te-res-SAN-te","È interessante.","Aggettivi"],
["noioso","aburrido","no-JO-zo","È noioso.","Aggettivi"],
["pericoloso","peligroso","pe-ri-ko-LO-zo","È pericoloso.","Aggettivi"],
["necessario","necesario","ne-ches-SA-rjo","È necessario.","Aggettivi"],
["speciale","especial","spe-CHA-le","È speciale.","Aggettivi"],
// ── ADVERBS & CONNECTORS ──────────────────────────────────────
["non","no / no","NON","Non capisco.","Avverbi"],
["molto","mucho / muy","MOL-to","Molto bene.","Avverbi"],
["poco","poco","PO-ko","Un po' di latte.","Avverbi"],
["più","más","PIÙ","Voglio di più.","Avverbi"],
["meno","menos","ME-no","Meno male!","Avverbi"],
["già","ya","JA","L'ho già fatto.","Avverbi"],
["ancora","todavía / aún / otra vez","an-KO-ra","Ancora una volta.","Avverbi"],
["sempre","siempre","SEM-pre","Ti voglio sempre bene.","Avverbi"],
["mai","nunca / jamás","MAI","Non lo faccio mai.","Avverbi"],
["spesso","a menudo / frecuentemente","SPES-so","Vengo spesso.","Avverbi"],
["subito","enseguida / inmediatamente","SU-bi-to","Vengo subito.","Avverbi"],
["adesso","ahora","a-DES-so","Cosa fai adesso?","Avverbi"],
["ora","ahora / hora","O-ra","Vieni ora.","Avverbi"],
["poi","luego / después","POI","Prima mangio, poi esco.","Avverbi"],
["dopo","después","DO-po","Ci vediamo dopo.","Avverbi"],
["prima","antes / primero","PRI-ma","Prima di tutto.","Avverbi"],
["presto","pronto / temprano","PRES-to","Arriva presto.","Avverbi"],
["tardi","tarde","TAR-di","È tardi.","Avverbi"],
["insieme","juntos / a la vez","in-SJE-me","Andiamo insieme.","Avverbi"],
["qui","aquí","KWI","Vieni qui.","Avverbi"],
["là","allá / ahí","LA","Guarda là.","Avverbi"],
["dove","donde","DO-ve","Dove sei?","Avverbi"],
["quando","cuando","KWAN-do","Quando arrivi?","Avverbi"],
["come","cómo / como","KO-me","Come stai?","Avverbi"],
["perché","por qué / porque","per-KÈ","Perché no?","Avverbi"],
["quanto","cuánto / cuanto","KWAN-to","Quanto costa?","Avverbi"],
["quale","cuál / qué","KWA-le","Quale preferisci?","Avverbi"],
["quasi","casi","KWA-zi","Quasi pronto.","Avverbi"],
["forse","quizás / tal vez","FOR-se","Forse domani.","Avverbi"],
["certamente","ciertamente / claro","cher-ta-MEN-te","Certamente!","Avverbi"],
["probabilmente","probablemente","pro-bab-bil-MEN-te","Probabilmente sì.","Avverbi"],
["davvero","de verdad / realmente","dav-VE-ro","Davvero?","Avverbi"],
["proprio","precisamente / justo","PRO-prjo","Proprio così.","Avverbi"],
["abbastanza","bastante","ab-bas-TAN-tsa","È abbastanza grande.","Avverbi"],
["troppo","demasiado","TROP-po","È troppo caro.","Avverbi"],
["solo","solo / solamente","SO-lo","Solo un momento.","Avverbi"],
["anche","también / incluso","AN-ke","Anch'io vengo.","Avverbi"],
["nemmeno","ni siquiera / tampoco","nem-ME-no","Nemmeno io lo so.","Avverbi"],
["però","pero / sin embargo","pe-RÒ","Mi piace, però è caro.","Avverbi"],
["quindi","entonces / por lo tanto","KWIN-di","Quindi cosa facciamo?","Avverbi"],
["allora","entonces / bueno","al-LO-ra","Allora, andiamo?","Avverbi"],
["comunque","de todas formas / igual","ko-MUN-kwe","Comunque, ci vediamo.","Avverbi"],
["invece","en cambio / en vez de","in-VE-che","Io invece vado.","Avverbi"],
["ancora","aún / todavía","an-KO-ra","Non ancora.","Avverbi"],
["ormai","ya (sin remedio)","or-MAI","Ormai è fatta.","Avverbi"],
["purtroppo","desgraciadamente","pur-TROP-po","Purtroppo non posso.","Avverbi"],
["fortunatamente","afortunadamente","for-tu-na-ta-MEN-te","Fortunatamente è andato bene.","Avverbi"],
["normalmente","normalmente","nor-mal-MEN-te","Normalmente lavoro da casa.","Avverbi"],
["finalmente","finalmente / por fin","fi-nal-MEN-te","Finalmente!","Avverbi"],
["improvvisamente","de repente","im-prov-vi-za-MEN-te","È arrivato improvvisamente.","Avverbi"],
["semplicemente","simplemente","sem-pli-che-MEN-te","Semplicemente bello.","Avverbi"],
// ── PREPOSITIONS & ARTICLES ───────────────────────────────────
["di","de","DI","Sono di Roma.","Preposizioni"],
["a","a / en","A","Vado a Roma.","Preposizioni"],
["in","en","IN","Vivo in Italia.","Preposizioni"],
["su","sobre / en","SU","Il libro è sul tavolo.","Preposizioni"],
["con","con","KON","Vengo con te.","Preposizioni"],
["per","para / por","PER","È per te.","Preposizioni"],
["da","de / desde / por","DA","Vengo da Roma.","Preposizioni"],
["tra / fra","entre","TRA","Tra me e te.","Preposizioni"],
["verso","hacia","VER-so","Verso le tre.","Preposizioni"],
["senza","sin","SEN-tsa","Senza di te.","Preposizioni"],
["dopo","después de","DO-po","Dopo pranzo.","Preposizioni"],
["prima","antes de","PRI-ma","Prima di cena.","Preposizioni"],
["durante","durante","du-RAN-te","Durante la notte.","Preposizioni"],
["secondo","según","se-KON-do","Secondo me.","Preposizioni"],
["il","el","IL","Il cane.","Articoli"],
["la","la","LA","La casa.","Articoli"],
["lo","el (ante s+cons.)","LO","Lo studente.","Articoli"],
["i","los","I","I libri.","Articoli"],
["le","las","LE","Le ragazze.","Articoli"],
["gli","los (m. antes vocal)","LJI","Gli amici.","Articoli"],
["un","un / uno","UN","Un caffè.","Articoli"],
["una","una","U-na","Una pizza.","Articoli"],
// ── PRONOUNS ─────────────────────────────────────────────────
["io","yo","IO","Io parlo italiano.","Pronomi"],
["tu","tú","TU","Tu parli bene.","Pronomi"],
["lui","él","LUI","Lui è italiano.","Pronomi"],
["lei","ella / usted","LEI","Lei è italiana.","Pronomi"],
["noi","nosotros","NOI","Noi andiamo.","Pronomi"],
["voi","vosotros","VOI","Voi capite?","Pronomi"],
["loro","ellos / ellas","LO-ro","Loro vengono.","Pronomi"],
["mi","me","MI","Mi chiamo Marco.","Pronomi"],
["ti","te","TI","Ti aspetto.","Pronomi"],
["si","se","SI","Si chiama Anna.","Pronomi"],
["ci","nos / allí","CHI","Ci vediamo.","Pronomi"],
["vi","os / les","VI","Vi presento Marco.","Pronomi"],
["mio","mío / mi","MIO","Il mio libro.","Pronomi"],
["tuo","tuyo / tu","TUO","Il tuo telefono.","Pronomi"],
["suo","suyo / su","SUO","Il suo nome.","Pronomi"],
["nostro","nuestro","NOS-tro","La nostra casa.","Pronomi"],
["vostro","vuestro","VOS-tro","Il vostro problema.","Pronomi"],
["questo","este / esto","KWES-to","Questo libro.","Pronomi"],
["quello","ese / aquel","KWEL-lo","Quello è bello.","Pronomi"],
["qualcosa","algo","kwal-KO-za","Vuoi qualcosa?","Pronomi"],
["qualcuno","alguien","kwal-KU-no","Qualcuno ti cerca.","Pronomi"],
["nessuno","nadie / ninguno","nes-SU-no","Non c'è nessuno.","Pronomi"],
["tutto","todo","TUT-to","Ho mangiato tutto.","Pronomi"],
["tutti","todos","TUT-ti","Tutti vengono.","Pronomi"],
["niente","nada","NJEN-te","Non ho niente.","Pronomi"],
["altro","otro","AL-tro","Un altro caffè.","Pronomi"],
["stesso","mismo","STES-so","La stessa cosa.","Pronomi"],
// ── COMMON PHRASES ────────────────────────────────────────────
["per favore","por favor","per fa-VO-re","Un caffè, per favore.","Frasi"],
["grazie","gracias","GRA-tsje","Grazie mille!","Frasi"],
["prego","de nada","PRE-go","Prego!","Frasi"],
["scusa / scusi","perdona / disculpa","SKU-za","Scusa il ritardo.","Frasi"],
["mi dispiace","lo siento","mi dis-PJA-che","Mi dispiace tanto.","Frasi"],
["buongiorno","buenos días","bwon-JOR-no","Buongiorno!","Frasi"],
["buonasera","buenas tardes / noches","bwo-na-SE-ra","Buonasera!","Frasi"],
["buonanotte","buenas noches","bwo-na-NOT-te","Buonanotte!","Frasi"],
["ciao","hola / adiós","CHAO","Ciao!","Frasi"],
["arrivederci","hasta luego","ar-ri-ve-DER-chi","Arrivederci!","Frasi"],
["come stai?","¿cómo estás?","KO-me STAI","Come stai oggi?","Frasi"],
["sto bene","estoy bien","STO BE-ne","Sto bene, grazie.","Frasi"],
["non capisco","no entiendo","non ka-PIS-ko","Non capisco, ripeti?","Frasi"],
["puoi ripetere?","¿puedes repetir?","PWOI ri-pe-TE-re","Puoi ripetere lentamente?","Frasi"],
["parli italiano?","¿hablas italiano?","PAR-li i-tal-JA-no","Parli italiano?","Frasi"],
["non parlo bene","no hablo bien","non PAR-lo BE-ne","Non parlo bene italiano.","Frasi"],
["quanto costa?","¿cuánto cuesta?","KWAN-to KOS-ta","Quanto costa questo?","Frasi"],
["dov'è…?","¿dónde está…?","do-VÈ","Dov'è il bagno?","Frasi"],
["vorrei…","quisiera… / me gustaría","vor-REI","Vorrei un tavolo.","Frasi"],
["ho fame","tengo hambre","O FA-me","Ho fame!","Frasi"],
["ho sete","tengo sed","O SE-te","Ho sete.","Frasi"],
["ho freddo","tengo frío","O FRED-do","Ho freddo.","Frasi"],
["ho caldo","tengo calor","O KAL-do","Ho caldo.","Frasi"],
["mi piace","me gusta","mi PJA-che","Mi piace l'Italia.","Frasi"],
["non mi piace","no me gusta","non mi PJA-che","Non mi piace il freddo.","Frasi"],
["non lo so","no lo sé","non lo SO","Non lo so.","Frasi"],
["capito!","¡entendido!","ka-PI-to","Sì, capito!","Frasi"],
["d'accordo","de acuerdo / vale","dak-KOR-do","D'accordo!","Frasi"],
["magari","ojalá / quizás / claro","ma-GA-ri","Magari!","Frasi"],
["meno male","menos mal / qué suerte","ME-no MA-le","Meno male che sei arrivato.","Frasi"],
["in bocca al lupo","¡mucha suerte!","in BOK-ka al LU-po","In bocca al lupo!","Frasi"],
["crepi!","(respuesta a 'in bocca al lupo')","KRE-pi","Crepi!","Frasi"],
["che peccato","qué lástima","ke pek-KA-to","Che peccato!","Frasi"],
["per esempio","por ejemplo","per e-ZEM-pjo","Per esempio, Roma.","Frasi"],
["cioè","es decir / o sea","CHO-È","Cioè, non voglio.","Frasi"],
["però","pero / sin embargo","pe-RÒ","Mi piace, però è caro.","Frasi"],
["anche se","aunque","AN-ke se","Vengo anche se stanco.","Frasi"],
["di solito","normalmente / por lo general","di SO-li-to","Di solito mangio a casa.","Frasi"],
["più o meno","más o menos","PJÙ o ME-no","Più o meno.","Frasi"],
["da solo","solo / por cuenta propia","da SO-lo","Vivo da solo.","Frasi"],
["in realtà","en realidad","in re-al-TA","In realtà non lo so.","Frasi"],
["tra poco","dentro de poco / pronto","tra PO-ko","Arrivo tra poco.","Frasi"],
["per caso","por casualidad","per KA-zo","Hai per caso le chiavi?","Frasi"],
["a proposito","a propósito / por cierto","a pro-PO-zi-to","A proposito, hai visto Marco?","Frasi"],
["fa niente","no importa / no pasa nada","fa NJEN-te","Fa niente!","Frasi"],
["lascia perdere","olvídalo / déjalo estar","LA-sha PER-de-re","Lascia perdere.","Frasi"],
// ── NUMBERS ──────────────────────────────────────────────────
["uno","uno","U-no","Uno, due, tre.","Numeri"],
["due","dos","DU-e","Due caffè.","Numeri"],
["tre","tres","TRE","Tre giorni.","Numeri"],
["quattro","cuatro","KWAT-tro","Quattro persone.","Numeri"],
["cinque","cinco","CHIN-kwe","Cinque minuti.","Numeri"],
["sei","seis","SEI","Sono le sei.","Numeri"],
["sette","siete","SET-te","Sette giorni.","Numeri"],
["otto","ocho","OT-to","Otto ore.","Numeri"],
["nove","nueve","NO-ve","Nove mesi.","Numeri"],
["dieci","diez","DJE-chi","Dieci euro.","Numeri"],
["venti","veinte","VEN-ti","Venti anni.","Numeri"],
["trenta","treinta","TREN-ta","Trenta minuti.","Numeri"],
["cento","cien / ciento","CHEN-to","Cento euro.","Numeri"],
["mille","mil","MIL-le","Mille grazie.","Numeri"],
["primo","primero","PRI-mo","Il primo.","Numeri"],
["secondo","segundo","se-KON-do","Il secondo.","Numeri"],
["terzo","tercero","TER-tso","Il terzo.","Numeri"],
// ── BODY ─────────────────────────────────────────────────────
["testa","cabeza","TES-ta","Ho mal di testa.","Corpo"],
["occhio","ojo","OK-kjo","Gli occhi azzurri.","Corpo"],
["orecchio","oreja / oído","o-REK-kjo","Ho mal d'orecchio.","Corpo"],
["naso","nariz","NA-zo","Ho il naso chiuso.","Corpo"],
["bocca","boca","BOK-ka","Apri la bocca.","Corpo"],
["dente","diente","DEN-te","Ho mal di denti.","Corpo"],
["lingua","lengua / idioma","LIN-gwa","Parla molte lingue.","Corpo"],
["gola","garganta","GO-la","Ho mal di gola.","Corpo"],
["spalla","hombro","SPAL-la","Ho la spalla rotta.","Corpo"],
["braccio","brazo","BRAT-cho","Ho il braccio rotto.","Corpo"],
["mano","mano","MA-no","Mi fa male la mano.","Corpo"],
["dito","dedo","DI-to","Ho tagliato il dito.","Corpo"],
["schiena","espalda","SKJE-na","Ho mal di schiena.","Corpo"],
["pancia","barriga / vientre","PAN-cha","Ho mal di pancia.","Corpo"],
["gamba","pierna","GAM-ba","Ho la gamba rotta.","Corpo"],
["piede","pie","PJE-de","Ho il piede gonfio.","Corpo"],
["cuore","corazón","KWO-re","Il mio cuore batte forte.","Corpo"],
["stomaco","estómago","STO-ma-ko","Ho mal di stomaco.","Corpo"],
["sangue","sangre","SAN-gwe","Ha perso sangue.","Corpo"],
// ── PLACES ───────────────────────────────────────────────────
["Italia","Italia","i-TA-lja","Vivo in Italia.","Luoghi"],
["Roma","Roma","RO-ma","Roma è bellissima.","Luoghi"],
["Milano","Milán","mi-LA-no","Lavoro a Milano.","Luoghi"],
["Napoli","Nápoles","NA-po-li","La pizza di Napoli.","Luoghi"],
["Europa","Europa","eu-RO-pa","L'Europa è grande.","Luoghi"],
["nord","norte","NORD","Nel nord d'Italia.","Luoghi"],
["sud","sur","SUD","Il sud è caldo.","Luoghi"],
["est","este","EST","A est di Roma.","Luoghi"],
["ovest","oeste","O-vest","L'ovest è lontano.","Luoghi"],
["centro","centro","CHEN-tro","Abito in centro.","Luoghi"],
["periferia","periferia / afueras","pe-ri-fe-RIA","Vivo in periferia.","Luoghi"],
["appartamento","apartamento / piso","ap-par-ta-MEN-to","Il mio appartamento.","Luoghi"],
["camera","habitación","KA-me-ra","La mia camera.","Luoghi"],
["cucina","cocina","ku-CHI-na","La cucina è grande.","Luoghi"],
["bagno","baño","BAN-jo","Dov'è il bagno?","Luoghi"],
["salone","salón / sala de estar","sa-LO-ne","Il salone è grande.","Luoghi"],
["giardino","jardín","jar-DI-no","Ho un bel giardino.","Luoghi"],
["garage","garaje","ga-RAJ","La macchina in garage.","Luoghi"],
["aeroporto","aeropuerto","a-e-ro-POR-to","All'aeroporto.","Luoghi"],
["stazione","estación","sta-TSJO-ne","Alla stazione.","Luoghi"],
["fermata","parada","fer-MA-ta","La fermata dell'autobus.","Luoghi"],
["autostrada","autopista","au-tos-TRA-da","Sull'autostrada.","Luoghi"],
["banca","banco","BAN-ka","Vado in banca.","Luoghi"],
["posta","correos","POS-ta","All'ufficio postale.","Luoghi"],
["farmacia","farmacia","far-ma-CHI-a","Vado in farmacia.","Luoghi"],
["chiesa","iglesia","KJE-za","La chiesa è vecchia.","Luoghi"],
["museo","museo","mu-ZE-o","Visito il museo.","Luoghi"],
["parco","parque","PAR-ko","Nel parco.","Luoghi"],
["spiaggia","playa","SPJAD-ja","Vado in spiaggia.","Luoghi"],
["bosco","bosque","BOS-ko","Nel bosco.","Luoghi"],
["lago","lago","LA-go","Sul lago di Como.","Luoghi"],
// ── FOOD & DRINK ──────────────────────────────────────────────
["pasta","pasta","PAS-ta","La pasta è buona.","Cibo"],
["pizza","pizza","PIT-tsa","Una pizza margherita.","Cibo"],
["riso","arroz","RI-zo","Il risotto milanese.","Cibo"],
["pane","pan","PA-ne","Un pezzo di pane.","Cibo"],
["formaggio","queso","for-MAD-jo","Formaggio italiano.","Cibo"],
["uovo","huevo","WO-vo","Le uova al mattino.","Cibo"],
["pollo","pollo","POL-lo","Il pollo arrosto.","Cibo"],
["olio","aceite","O-ljo","Olio d'oliva.","Cibo"],
["burro","mantequilla","BUR-ro","Attn: burro ≠ burro en esp.","Cibo"],
["sale","sal","SA-le","Aggiungi il sale.","Cibo"],
["zucchero","azúcar","TSUK-ke-ro","Senza zucchero.","Cibo"],
["latte","leche","LAT-te","Un caffè con latte.","Cibo"],
["succo","zumo / jugo","SUK-ko","Un succo d'arancia.","Cibo"],
["tè","té","TÈ","Un tè caldo.","Cibo"],
["mela","manzana","ME-la","Una mela al giorno.","Cibo"],
["arancia","naranja","a-RAN-cha","Il succo d'arancia.","Cibo"],
["pomodoro","tomate","po-mo-DO-ro","La salsa di pomodoro.","Cibo"],
["insalata","ensalada","in-sa-LA-ta","Un'insalata fresca.","Cibo"],
["minestra","sopa / caldo","mi-NES-tra","La minestra è calda.","Cibo"],
["dolce","dulce / postre","DOL-che","Un dolce per favore.","Cibo"],
["gelato","helado","je-LA-to","Un gelato al cioccolato.","Cibo"],
["cioccolato","chocolate","chok-ko-LA-to","Cioccolato fondente.","Cibo"],
["pranzo","almuerzo / comida","PRAN-tso","È ora di pranzo.","Cibo"],
["cena","cena","CHE-na","Vieni a cena?","Cibo"],
["colazione","desayuno","ko-la-TSJO-ne","Faccio colazione.","Cibo"],
["menù","menú","me-NU","Posso vedere il menù?","Cibo"],
["bicchiere","vaso / copa","bik-KJE-re","Un bicchiere d'acqua.","Cibo"],
["bottiglia","botella","bot-TI-lja","Una bottiglia di vino.","Cibo"],
["piatto","plato","PJAT-to","Un piatto di pasta.","Cibo"],
["coltello","cuchillo","kol-TEL-lo","Il coltello è affilato.","Cibo"],
["forchetta","tenedor","for-KET-ta","La forchetta.","Cibo"],
["cucchiaio","cuchara","kuk-KJA-jo","Il cucchiaio da minestra.","Cibo"],
// ── CLOTHES ──────────────────────────────────────────────────
["vestito","vestido / traje","ves-TI-to","Un bel vestito.","Vestiti"],
["camicia","camisa","ka-MI-cha","Una camicia bianca.","Vestiti"],
["pantaloni","pantalones","pan-ta-LO-ni","I pantaloni neri.","Vestiti"],
["gonna","falda","GON-na","Una gonna corta.","Vestiti"],
["maglione","jersey / suéter","mal-JO-ne","Un maglione caldo.","Vestiti"],
["giacca","chaqueta / chaquetón","JAK-ka","La giacca invernale.","Vestiti"],
["scarpe","zapatos","SKAR-pe","Nuove scarpe.","Vestiti"],
["cappello","sombrero / gorro","kap-PEL-lo","Un cappello estivo.","Vestiti"],
["borsa","bolso / bolsa","BOR-sa","La mia borsa.","Vestiti"],
// ── WORK & STUDY ─────────────────────────────────────────────
["riunione","reunión","riu-NJO-ne","Ho una riunione.","Lavoro"],
["progetto","proyecto","pro-JET-to","Il nostro progetto.","Lavoro"],
["cliente","cliente","kli-EN-te","Il cliente è soddisfatto.","Lavoro"],
["collega","colega / compañero","kol-LE-ga","Il mio collega.","Lavoro"],
["capo","jefe / jefa","KA-po","Il mio capo.","Lavoro"],
["stipendio","sueldo / salario","sti-PEN-djo","Il mio stipendio.","Lavoro"],
["contratto","contrato","kon-TRAT-to","Ho firmato il contratto.","Lavoro"],
["curriculum","currículum","kur-RI-ku-lum","Il mio curriculum.","Lavoro"],
["intervista","entrevista","in-ter-VIS-ta","Ho un'intervista domani.","Lavoro"],
["materia","materia / asignatura","ma-TE-rja","La mia materia preferita.","Lavoro"],
["esame","examen","e-ZA-me","Ho un esame domani.","Lavoro"],
["voto","nota / calificación","VO-to","Ho preso un bel voto.","Lavoro"],
["professore","profesor","pro-fes-SO-re","Il professore spiega bene.","Lavoro"],
["studente","estudiante","stu-DEN-te","Sono uno studente.","Lavoro"],
// ── TECHNOLOGY ───────────────────────────────────────────────
["schermo","pantalla","SKER-mo","Lo schermo è rotto.","Tecnologia"],
["tastiera","teclado","tas-TJE-ra","La tastiera del pc.","Tecnologia"],
["mouse","ratón","MAUS","Il mouse non funziona.","Tecnologia"],
["app","aplicación","APP","Scarico l'app.","Tecnologia"],
["file","archivo / fichero","FAIL","Salvo il file.","Tecnologia"],
["password","contraseña","PAS-word","La password è sicura.","Tecnologia"],
["email","correo electrónico","I-meil","Ti mando un'email.","Tecnologia"],
["rete","red","RE-te","La rete wifi.","Tecnologia"],
["batteria","batería","bat-te-RIA","La batteria è scarica.","Tecnologia"],
["caricatore","cargador","ka-ri-ka-TO-re","Ho bisogno del caricatore.","Tecnologia"],
["cuffia","auricular / auriculares","KUF-fja","Le cuffie wireless.","Tecnologia"],
["stampante","impresora","stam-PAN-te","La stampante è rotta.","Tecnologia"],
// ── TRAVEL ───────────────────────────────────────────────────
["passaporto","pasaporte","pas-sa-POR-to","Il mio passaporto.","Viaggio"],
["biglietto","billete / entrada","bil-JET-to","Il biglietto del treno.","Viaggio"],
["prenotazione","reserva / reservación","pre-no-ta-TSJO-ne","Ho una prenotazione.","Viaggio"],
["valigia","maleta","va-LI-ja","Ho perso la valigia.","Viaggio"],
["zaino","mochila","TSAI-no","Il mio zaino.","Viaggio"],
["albergo","hotel","al-BER-go","Abito in albergo.","Viaggio"],
["ostello","albergue / hostal","os-TEL-lo","Un ostello economico.","Viaggio"],
["camera singola","habitación individual","KA-me-ra SIN-go-la","Camera singola per favore.","Viaggio"],
["camera doppia","habitación doble","KA-me-ra DOP-pja","Camera doppia per favore.","Viaggio"],
["ritardo","retraso","ri-TAR-do","Il treno è in ritardo.","Viaggio"],
["coincidenza","correspondencia / conexión","ko-in-chi-DEN-tsa","Ho perso la coincidenza.","Viaggio"],
["dogana","aduana","do-GA-na","Controllo doganale.","Viaggio"],
["turista","turista","tu-RIS-ta","Sono un turista.","Viaggio"],
["guida","guía","GWI-da","Una guida turistica.","Viaggio"],
["cartina","mapa","kar-TI-na","Hai una cartina?","Viaggio"],
];
// ── EMOTIONS & PERSONALITY ────────────────────────────────────
["emozione","emoción","e-mo-TSJO-ne","Le emozioni umane.","Emozioni"],
["gioia","alegría","JO-ja","Che gioia!","Emozioni"],
["rabbia","rabia / ira","RAB-bja","Sento molta rabbia.","Emozioni"],
["tristezza","tristeza","tris-TET-tsa","La tristezza passa.","Emozioni"],
["ansia","ansiedad","AN-sja","Ho molta ansia.","Emozioni"],
["stress","estrés","STRES","Sono sotto stress.","Emozioni"],
["sorpresa","sorpresa","sor-PRE-za","Che sorpresa!","Emozioni"],
["delusione","decepción","de-lu-ZJO-ne","Sono deluso.","Emozioni"],
["entusiasmo","entusiasmo","en-tu-ZJAZ-mo","Pieno di entusiasmo.","Emozioni"],
["orgoglio","orgullo","or-GOL-jo","Sono orgoglioso.","Emozioni"],
["vergogna","vergüenza","ver-GON-ja","Che vergogna!","Emozioni"],
["gelosia","celos","je-lo-ZI-a","È pieno di gelosia.","Emozioni"],
["odio","odio","O-djo","L'odio fa male.","Emozioni"],
["rispetto","respeto","ris-PET-to","Merita rispetto.","Emozioni"],
["fiducia","confianza","fi-DU-cha","Ho fiducia in te.","Emozioni"],
["coraggio","coraje / valentía","ko-RAD-jo","Che coraggio!","Emozioni"],
["pazienza","paciencia","pa-TSJEN-tsa","Abbi pazienza.","Emozioni"],
["speranza","esperanza","spe-RAN-tsa","Ho ancora speranza.","Emozioni"],
["ottimista","optimista","ot-ti-MIS-ta","Sono ottimista.","Emozioni"],
["pessimista","pesimista","pes-si-MIS-ta","Non essere pessimista.","Emozioni"],
// ── ENVIRONMENT & NATURE ─────────────────────────────────────
["albero","árbol","AL-be-ro","Un albero alto.","Natura"],
["fiore","flor","FJO-re","Un bel fiore.","Natura"],
["erba","hierba / césped","ER-ba","L'erba verde.","Natura"],
["foglia","hoja","FOL-ja","Le foglie cadono.","Natura"],
["bosco","bosque","BOS-ko","Nel bosco.","Natura"],
["foresta","selva / bosque","fo-RES-ta","La foresta amazzonica.","Natura"],
["deserto","desierto","de-ZER-to","Il deserto del Sahara.","Natura"],
["isola","isla","I-zo-la","Un'isola tropicale.","Natura"],
["collina","colina","kol-LI-na","Sulle colline toscane.","Natura"],
["pianura","llanura","pja-NU-ra","La pianura padana.","Natura"],
["pietra","piedra","PJE-tra","Una pietra grande.","Natura"],
["sabbia","arena","SAB-bja","La sabbia della spiaggia.","Natura"],
["onda","ola","ON-da","Le onde del mare.","Natura"],
["nuvola","nube","NU-vo-la","Le nuvole nel cielo.","Natura"],
["temporale","tormenta","tem-po-RA-le","Arriva un temporale.","Natura"],
["arcobaleno","arcoíris","ar-ko-ba-LE-no","Che bell'arcobaleno!","Natura"],
["terremoto","terremoto","ter-re-MO-to","Un terremoto forte.","Natura"],
["vulcano","volcán","vul-KA-no","L'Etna è un vulcano.","Natura"],
["animale","animal","a-ni-MA-le","Un animale selvatico.","Natura"],
["cane","perro","KA-ne","Ho un cane.","Natura"],
["gatto","gato","GAT-to","Il mio gatto dorme.","Natura"],
["cavallo","caballo","ka-VAL-lo","Un cavallo bianco.","Natura"],
["uccello","pájaro","ut-CHEL-lo","L'uccello canta.","Natura"],
["pesce","pez / pescado","PE-she","Un pesce colorato.","Natura"],
["leone","león","le-O-ne","Il leone ruggisce.","Natura"],
["elefante","elefante","e-le-FAN-te","Un elefante enorme.","Natura"],
// ── SOCIETY & POLITICS ───────────────────────────────────────
["governo","gobierno","go-VER-no","Il governo italiano.","Società"],
["stato","estado","STA-to","Lo stato italiano.","Società"],
["legge","ley","LED-je","La legge è uguale.","Società"],
["diritto","derecho","di-RIT-to","Il diritto al lavoro.","Società"],
["elezione","elección","e-le-TSJO-ne","Le elezioni politiche.","Società"],
["politica","política","po-LI-ti-ka","La politica italiana.","Società"],
["economia","economía","e-ko-no-MIA","L'economia cresce.","Società"],
["società","sociedad","so-che-TA","La società moderna.","Società"],
["cultura","cultura","kul-TU-ra","La cultura italiana.","Società"],
["religione","religión","re-li-JO-ne","La religione cattolica.","Società"],
["lingua","lengua / idioma","LIN-gwa","Imparo la lingua.","Società"],
["nazione","nación","na-TSJO-ne","La nostra nazione.","Società"],
["frontiera","frontera","fron-TJE-ra","La frontiera doganale.","Società"],
["immigrazione","inmigración","im-mi-gra-TSJO-ne","Il fenomeno migratorio.","Società"],
["polizia","policía","po-LI-tsia","La polizia arriva.","Società"],
["ospedale","hospital","os-pe-DA-le","All'ospedale.","Società"],
["scuola","escuela","SKWO-la","La scuola pubblica.","Società"],
["chiesa","iglesia","KJE-za","La chiesa cattolica.","Società"],
["impresa","empresa","im-PRE-za","Una grande impresa.","Società"],
["industria","industria","in-DUS-trja","L'industria italiana.","Società"],
// ── DESCRIPTIONS: COLORS ─────────────────────────────────────
["rosso","rojo","ROS-so","Una rosa rossa.","Colori"],
["blu","azul","BLU","Il cielo è blu.","Colori"],
["verde","verde","VER-de","L'erba è verde.","Colori"],
["giallo","amarillo","JAL-lo","Un limone giallo.","Colori"],
["arancione","naranja","a-ran-CHO-ne","Un tramonto arancione.","Colori"],
["viola","morado / violeta","VJO-la","Un fiore viola.","Colori"],
["rosa","rosa","RO-za","Una rosa rosa.","Colori"],
["bianco","blanco","BJAN-ko","Un foglio bianco.","Colori"],
["nero","negro","NE-ro","Un gatto nero.","Colori"],
["grigio","gris","GRI-jo","Un cielo grigio.","Colori"],
["marrone","marrón / café","mar-RO-ne","Una borsa marrone.","Colori"],
["azzurro","azul claro / celeste","at-TSUR-ro","L'azzurro del mare.","Colori"],
// ── QUANTITIES & MEASURES ─────────────────────────────────────
["litro","litro","LI-tro","Un litro d'acqua.","Misure"],
["chilo","kilo","KI-lo","Un chilo di pasta.","Misure"],
["metro","metro","ME-tro","Dieci metri.","Misure"],
["chilometro","kilómetro","ki-LO-me-tro","Cento chilometri.","Misure"],
["grammo","gramo","GRAM-mo","Cento grammi.","Misure"],
["centimetro","centímetro","chen-TI-me-tro","Venti centimetri.","Misure"],
["ora","hora","O-ra","Un'ora di viaggio.","Misure"],
["minuto","minuto","mi-NU-to","Cinque minuti.","Misure"],
["secondo","segundo","se-KON-do","Trenta secondi.","Misure"],
["fila","fila / cola","FI-la","In fila al supermercato.","Misure"],
["paio","par","PA-jo","Un paio di scarpe.","Misure"],
["pezzo","trozo / pedazo","PET-tso","Un pezzo di torta.","Misure"],
// ── SHAPES & SPACE ───────────────────────────────────────────
["cerchio","círculo","CHER-kjo","Forma di cerchio.","Forme"],
["quadrato","cuadrado","kwa-DRA-to","Un quadrato perfetto.","Forme"],
["triangolo","triángulo","tri-AN-go-lo","Un triangolo rosso.","Forme"],
["rettangolo","rectángulo","ret-TAN-go-lo","Forma rettangolare.","Forme"],
["lato","lado","LA-to","I quattro lati.","Forme"],
["angolo","ángulo / rincón","AN-go-lo","L'angolo della strada.","Forme"],
["superficie","superficie","su-per-FI-che","La superficie del tavolo.","Forme"],
["profondità","profundidad","pro-fon-di-TA","La profondità del mare.","Forme"],
["larghezza","anchura","lar-GET-tsa","La larghezza del corridoio.","Forme"],
["altezza","altura","al-TET-tsa","L'altezza del palazzo.","Forme"],
["peso","peso","PE-zo","Il peso della valigia.","Forme"],
["volume","volumen","vo-LU-me","Il volume della stanza.","Forme"],
// ── VERBS EXTRA ──────────────────────────────────────────────
["raggiungere","alcanzar / llegar a","rad-JUN-je-re","Ho raggiunto l'obiettivo.","Verbi"],
["spingere","empujar","SPIN-je-re","Spingere o tirare?","Verbi"],
["tirare","tirar / jalar","ti-RA-re","Tirare la porta.","Verbi"],
["rompere","romper","ROM-pe-re","Ho rotto il bicchiere.","Verbi"],
["riparare","reparar / arreglar","ri-pa-RA-re","Ripara la bici.","Verbi"],
["costruire","construir","kos-TRU-i-re","Costruire una casa.","Verbi"],
["distruggere","destruir","dis-TRUD-je-re","Non distruggere.","Verbi"],
["crescere","crecer","KRESH-she-re","I bambini crescono.","Verbi"],
["aumentare","aumentar","au-men-TA-re","I prezzi aumentano.","Verbi"],
["diminuire","disminuir","di-mi-NU-i-re","I prezzi diminuiscono.","Verbi"],
["migliorare","mejorar","mil-jo-RA-re","Voglio migliorare.","Verbi"],
["peggiorare","empeorar","ped-jo-RA-re","La situazione peggiora.","Verbi"],
["sorridere","sonreír","sor-RI-de-re","Mi fai sorridere.","Verbi"],
["abbracciare","abrazar","ab-BRAT-cha-re","Ti abbraccio forte.","Verbi"],
["baciare","besar","ba-CHA-re","La bacia sulla guancia.","Verbi"],
["urlare","gritar","ur-LA-re","Non urlare.","Verbi"],
["sussurrare","susurrar","sus-sur-RA-re","Sussurra piano.","Verbi"],
["spiegare","explicar","spje-GA-re","Spiega bene.","Verbi"],
["tradurre","traducir","tra-DUR-re","Traduci per favore.","Verbi"],
["ringraziare","agradecer","rin-gra-TSJA-re","Ti ringrazio.","Verbi"],
["invitare","invitar","in-vi-TA-re","Ti invito a cena.","Verbi"],
["rifiutare","rechazar / negarse","ri-fju-TA-re","Ha rifiutato l'offerta.","Verbi"],
["accettare","aceptar","at-chet-TA-re","Accetto l'invito.","Verbi"],
["promettere","prometer","pro-MET-te-re","Te lo prometto.","Verbi"],
["mentire","mentir","men-TI-re","Non mentire.","Verbi"],
["scommettere","apostar","skom-MET-te-re","Scommetto che hai ragione.","Verbi"],
["scegliere","elegir","SHE-lje-re","Scegliere è difficile.","Verbi"],
["confrontare","comparar / confrontar","kon-fron-TA-re","Confronta i prezzi.","Verbi"],
["risolvere","resolver","ri-ZOL-ve-re","Risolvo il problema.","Verbi"],
["evitare","evitar","e-vi-TA-re","Evito il traffico.","Verbi"],
["rischiare","arriesgar","ris-KJA-re","Rischia tutto.","Verbi"],
["guadagnare","ganar","gwa-dan-JA-re","Guadagno bene.","Verbi"],
["investire","invertir","in-ves-TI-re","Investo in borsa.","Verbi"],
["risparmiare","ahorrar","ris-par-MJA-re","Devo risparmiare.","Verbi"],
["noleggiare","alquilar","no-led-JA-re","Noleggio una macchina.","Verbi"],
["affittare","alquilar","af-fit-TA-re","Affitto un appartamento.","Verbi"],
["firmare","firmar","fir-MA-re","Firma qui.","Verbi"],
["stampare","imprimir","stam-PA-re","Stampa il documento.","Verbi"],
["salvare","guardar / salvar","sal-VA-re","Salva il file.","Verbi"],
["caricare","cargar / subir","ka-ri-KA-re","Carica la batteria.","Verbi"],
["scaricare","descargar","ska-ri-KA-re","Scarica l'app.","Verbi"],
["collegare","conectar","kol-le-GA-re","Collega il cavo.","Verbi"],
["aggiornare","actualizar","ad-jor-NA-re","Aggiorna il sistema.","Verbi"],
// ── MORE NOUNS ────────────────────────────────────────────────
["obiettivo","objetivo","o-bjet-TI-vo","Raggiungo il mio obiettivo.","Sostantivi"],
["risultato","resultado","ri-zul-TA-to","Un buon risultato.","Sostantivi"],
["successo","éxito","suc-CHES-so","Ha avuto successo.","Sostantivi"],
["fallimento","fracaso","fal-li-MEN-to","Il fallimento insegna.","Sostantivi"],
["opportunità","oportunidad","op-por-tu-ni-TA","Una buona opportunità.","Sostantivi"],
["rischio","riesgo","RIS-kjo","È un rischio.","Sostantivi"],
["vantaggio","ventaja","van-TAD-jo","Qual è il vantaggio?","Sostantivi"],
["svantaggio","desventaja","zvan-TAD-jo","Uno svantaggio enorme.","Sostantivi"],
["accordo","acuerdo","ak-KOR-do","Siamo d'accordo.","Sostantivi"],
["contratto","contrato","kon-TRAT-to","Firmo il contratto.","Sostantivi"],
["regola","regla / norma","RE-go-la","Segui le regole.","Sostantivi"],
["abitudine","hábito / costumbre","a-bi-TU-di-ne","È un'abitudine.","Sostantivi"],
["tradizione","tradición","tra-di-TSJO-ne","La tradizione italiana.","Sostantivi"],
["usanza","costumbre / uso","u-ZAN-tsa","Un'usanza locale.","Sostantivi"],
["mistero","misterio","mis-TE-rjo","È un mistero.","Sostantivi"],
["segreto","secreto","se-GRE-to","Mantieni il segreto.","Sostantivi"],
["bugia","mentira","BU-ja","Dire una bugia.","Sostantivi"],
["verità","verdad","ve-ri-TA","La verità fa male.","Sostantivi"],
["motivo","motivo / razón","mo-TI-vo","Qual è il motivo?","Sostantivi"],
["scopo","propósito / objetivo","SKO-po","Qual è lo scopo?","Sostantivi"],
["metodo","método","ME-to-do","Il metodo giusto.","Sostantivi"],
["sistema","sistema","sis-TE-ma","Il sistema funziona.","Sostantivi"],
["processo","proceso","pro-CHES-so","Un lungo processo.","Sostantivi"],
["situazione","situación","si-twa-TSJO-ne","La situazione è difficile.","Sostantivi"],
["condizione","condición","kon-di-TSJO-ne","In buone condizioni.","Sostantivi"],
["posizione","posición","po-zi-TSJO-ne","La posizione giusta.","Sostantivi"],
["direzione","dirección","di-re-TSJO-ne","In quale direzione?","Sostantivi"],
["distanza","distancia","dis-TAN-tsa","Che distanza!","Sostantivi"],
["velocità","velocidad","ve-lo-chi-TA","La velocità del treno.","Sostantivi"],
["forza","fuerza","FOR-tsa","Con tutta la forza.","Sostantivi"],
["energia","energía","e-ner-JI-a","Ho poca energia.","Sostantivi"],
["potere","poder","po-TE-re","Il potere politico.","Sostantivi"],
["controllo","control","kon-TROL-lo","Ho il controllo.","Sostantivi"],
["responsabilità","responsabilidad","res-pon-sa-bi-li-TA","È mia responsabilità.","Sostantivi"],
["valore","valor","va-LO-re","Ha un grande valore.","Sostantivi"],
["qualità","calidad","kwa-li-TA","Alta qualità.","Sostantivi"],
["quantità","cantidad","kwan-ti-TA","Una grande quantità.","Sostantivi"],
["differenza","diferencia","dif-fe-REN-tsa","Qual è la differenza?","Sostantivi"],
["somiglianza","semejanza / parecido","so-mil-JAN-tsa","C'è una somiglianza.","Sostantivi"],
["esempio","ejemplo","e-ZEM-pjo","Per esempio.","Sostantivi"],
["tipo","tipo","TI-po","Che tipo sei?","Sostantivi"],
["genere","género / tipo","JE-ne-re","Che genere musicale?","Sostantivi"],
["aspetto","aspecto / apariencia","as-PET-to","L'aspetto fisico.","Sostantivi"],
["carattere","carácter","ka-RAT-te-re","Che bel carattere.","Sostantivi"],
["personalità","personalidad","per-so-na-li-TA","Una forte personalità.","Sostantivi"],
["opinione","opinión","o-pi-NJO-ne","Qual è la tua opinione?","Sostantivi"],
["argomento","argumento / tema","ar-go-MEN-to","L'argomento è complesso.","Sostantivi"],
["domanda","pregunta","do-MAN-da","Fai una domanda.","Sostantivi"],
["risposta","respuesta","ris-POS-ta","La risposta giusta.","Sostantivi"],
["informazione","información","in-for-ma-TSJO-ne","Ho bisogno di informazioni.","Sostantivi"],
["notizia","noticia","no-TI-tsja","Una brutta notizia.","Sostantivi"],
["giornale","periódico","jor-NA-le","Leggo il giornale.","Sostantivi"],
["rivista","revista","ri-VIS-ta","Una rivista di moda.","Sostantivi"],
["pagina","página","PA-ji-na","A pagina tre.","Sostantivi"],
["capitolo","capítulo","ka-PI-to-lo","Il primo capitolo.","Sostantivi"],
["poesia","poesía","po-e-ZI-a","Una bella poesia.","Sostantivi"],
["romanzo","novela","ro-MAN-tso","Un romanzo italiano.","Sostantivi"],
["teatro","teatro","te-A-tro","Andiamo a teatro.","Sostantivi"],
["concerto","concierto","kon-CHER-to","Un concerto stasera.","Sostantivi"],
["mostra","exposición","MOS-tra","Una mostra d'arte.","Sostantivi"],
];
// ── EXTRA VERBS & COMMON WORDS ───────────────────────────────
["indicare","indicar / señalar","in-di-KA-re","Indica la direzione.","Verbi"],
["spedire","enviar / mandar","spe-DI-re","Spedisco il pacco.","Verbi"],
["consegnare","entregar","kon-sen-JA-re","Consegna il lavoro.","Verbi"],
["prenotare","reservar","pre-no-TA-re","Prenoto il tavolo.","Verbi"],
["ordinare","ordenar / pedir","or-di-NA-re","Ordino la pizza.","Verbi"],
["servire","servir","ser-VI-re","Serve a qualcosa?","Verbi"],
["bastare","bastar / ser suficiente","bas-TA-re","Basta così!","Verbi"],
["mancare","faltar","man-KA-re","Mi manchi.","Verbi"],
["importare","importar","im-por-TA-re","Non importa.","Verbi"],
["funzionare","funcionar","fun-tsjo-NA-re","Non funziona.","Verbi"],
["dubitare","dudar","du-bi-TA-re","Ne dubito.","Verbi"],
["meritare","merecer","me-ri-TA-re","Lo merita.","Verbi"],
["sorprendere","sorprender","sor-PREN-de-re","Mi hai sorpreso.","Verbi"],
["preoccuparsi","preocuparse","pre-ok-ku-PAR-si","Non preoccuparti.","Verbi"],
["rilassarsi","relajarse","ri-las-SAR-si","Rilassati!","Verbi"],
["divertirsi","divertirse","di-ver-TIR-si","Mi diverto.","Verbi"],
["annoiarsi","aburrirse","an-no-JAR-si","Mi annoio.","Verbi"],
["innamorarsi","enamorarse","in-na-mo-RAR-si","Mi sono innamorato.","Verbi"],
["sposarsi","casarse","spo-ZAR-si","Si sposano a giugno.","Verbi"],
["separarsi","separarse","se-pa-RAR-si","Si sono separati.","Verbi"],
["traslocare","mudarse","traz-lo-KA-re","Traslochiamo a maggio.","Verbi"],
["viaggiare","viajar","vjad-JA-re","Mi piace viaggiare.","Verbi"],
["esplorare","explorar","es-plo-RA-re","Esploro la città.","Verbi"],
["scoprire","descubrir","sko-PRI-re","Ho scoperto un posto.","Verbi"],
["visitare","visitar","vi-zi-TA-re","Visito il museo.","Verbi"],
["fotografare","fotografiar","fo-to-gra-FA-re","Fotografo tutto.","Verbi"],
["disegnare","dibujar","di-zen-JA-re","Disegno bene.","Verbi"],
["dipingere","pintar","di-PIN-je-re","Dipingo con acquerelli.","Verbi"],
["cantare","cantar","kan-TA-re","Canto sotto la doccia.","Verbi"],
["ballare","bailar","bal-LA-re","Ti piace ballare?","Verbi"],
["suonare","tocar (instrumento)","swo-NA-re","Suono la chitarra.","Verbi"],
["recitare","actuar / recitar","re-chi-TA-re","Recita in teatro.","Verbi"],
["guidare","conducir / manejar","gwi-DA-re","Guido ogni giorno.","Verbi"],
["parcheggiare","aparcar / estacionar","par-ked-JA-re","Dove parcheggio?","Verbi"],
["nuotare","nadar","nwo-TA-re","Nuoto bene.","Verbi"],
["sciare","esquiar","SHA-re","Scio in montagna.","Verbi"],
["allenarsi","entrenarse","al-le-NAR-si","Mi alleno ogni giorno.","Verbi"],
["riposarsi","descansar","ri-po-ZAR-si","Riposati un po'.","Verbi"],
["svegliarsi","despertarse","zvel-JAR-si","Mi sveglio alle 7.","Verbi"],
["lavarsi","lavarse","la-VAR-si","Mi lavo le mani.","Verbi"],
["vestirsi","vestirse","ves-TIR-si","Mi vesto in fretta.","Verbi"],
["truccarsi","maquillarse","truk-KAR-si","Si trucca ogni mattina.","Verbi"],
["pettinarsi","peinarse","pet-ti-NAR-si","Si pettina i capelli.","Verbi"],
// ── ADDITIONAL NOUNS ─────────────────────────────────────────
["vita quotidiana","vida cotidiana","VI-ta kwoti-DJA-na","La vita quotidiana.","Sostantivi"],
["abitudini","hábitos","a-bi-TU-di-ni","Le mie abitudini.","Sostantivi"],
["benessere","bienestar","be-NES-se-re","Il benessere fisico.","Sostantivi"],
["equilibrio","equilibrio","e-kwi-LI-brjo","Trovare l'equilibrio.","Sostantivi"],
["ritmo","ritmo","RIT-mo","Il ritmo della città.","Sostantivi"],
["rumore","ruido","ru-MO-re","Che rumore!","Sostantivi"],
["silenzio","silencio","si-LEN-tsjo","Silenzio per favore.","Sostantivi"],
["odore","olor","o-DO-re","Che buon odore!","Sostantivi"],
["sapore","sabor","sa-PO-re","Che buon sapore!","Sostantivi"],
["tatto","tacto","TAT-to","Senso del tatto.","Sostantivi"],
["vista","vista / visión","VIS-ta","Che bella vista!","Sostantivi"],
["suono","sonido","SWO-no","Un suono strano.","Sostantivi"],
["attenzione","atención","at-ten-TSJO-ne","Attenzione!","Sostantivi"],
["cura","cuidado / cura","KU-ra","Con cura.","Sostantivi"],
["pericolo","peligro","pe-RI-ko-lo","È un pericolo.","Sostantivi"],
["sicurezza","seguridad","si-ku-RET-tsa","La sicurezza prima di tutto.","Sostantivi"],
["urgenza","urgencia","ur-JEN-tsa","È un'urgenza.","Sostantivi"],
["emergenza","emergencia","e-mer-JEN-tsa","In caso di emergenza.","Sostantivi"],
["cambiamento","cambio","kam-bja-MEN-to","Un cambiamento importante.","Sostantivi"],
["sviluppo","desarrollo","zvi-LUP-po","Lo sviluppo sostenibile.","Sostantivi"],
["progresso","progreso","pro-GRES-so","Il progresso tecnologico.","Sostantivi"],
["futuro","futuro","fu-TU-ro","Il futuro è incerto.","Sostantivi"],
["passato","pasado","pas-SA-to","Dimentica il passato.","Sostantivi"],
["presente","presente","pre-ZEN-te","Vivi nel presente.","Sostantivi"],
["inizio","inicio / comienzo","i-NI-tsjo","All'inizio era difficile.","Sostantivi"],
["fine","fin / final","FI-ne","Alla fine tutto bene.","Sostantivi"],
["centro","centro","CHEN-tro","Il centro della città.","Sostantivi"],
["bordo","borde / orilla","BOR-do","Sul bordo del precipizio.","Sostantivi"],
["fondo","fondo","FON-do","In fondo al mare.","Sostantivi"],
["superficie","superficie","su-per-FI-che","La superficie è liscia.","Sostantivi"],
["spazio","espacio","SPA-tsjo","C'è poco spazio.","Sostantivi"],
["confine","frontera / límite","kon-FI-ne","Il confine tra stati.","Sostantivi"],
["clima","clima","KLI-ma","Il clima mediterraneo.","Sostantivi"],
["temperatura","temperatura","tem-pe-ra-TU-ra","La temperatura sale.","Sostantivi"],
["umidità","humedad","u-mi-di-TA","Alta umidità.","Sostantivi"],
["previsione","previsión / pronóstico","pre-vi-ZJO-ne","Le previsioni del tempo.","Sostantivi"],
["ondata","ola","on-DA-ta","Un'ondata di calore.","Sostantivi"],
["incendio","incendio","in-CHEN-djo","Un incendio boschivo.","Sostantivi"],
["inondazione","inundación","i-non-da-TSJO-ne","Un'inondazione grave.","Sostantivi"],
["multa","multa","MUL-ta","Ho preso una multa.","Sostantivi"],
["patente","permiso de conducir","pa-TEN-te","La patente di guida.","Sostantivi"],
["assicurazione","seguro","as-si-ku-ra-TSJO-ne","L'assicurazione auto.","Sostantivi"],
["imposta","impuesto","im-POS-ta","Le imposte sul reddito.","Sostantivi"],
["tassa","tasa / impuesto","TAS-sa","Le tasse universitarie.","Sostantivi"],
["affitto","alquiler / arriendo","af-FIT-to","Pago l'affitto.","Sostantivi"],
["mutuo","hipoteca","MU-two","Ho un mutuo.","Sostantivi"],
["busta paga","nómina","BUS-ta PA-ga","La busta paga mensile.","Sostantivi"],
["fattura","factura","fat-TU-ra","Emetto la fattura.","Sostantivi"],
["ricevuta","recibo","ri-che-VU-ta","Conserva la ricevuta.","Sostantivi"],
["scontrino","ticket / tiquete","skon-TRI-no","Vuole lo scontrino?","Sostantivi"],
["carta di credito","tarjeta de crédito","KAR-ta di KRE-di-to","Pago con carta.","Sostantivi"],
["bancomat","cajero automático / tarjeta débito","BAN-ko-mat","Prelevo al bancomat.","Sostantivi"],
["banca","banco","BAN-ka","Vado in banca.","Sostantivi"],
["conto","cuenta","KON-to","Il mio conto in banca.","Sostantivi"],
["interesse","interés","in-te-RES-se","Gli interessi bancari.","Sostantivi"],
["investimento","inversión","in-ves-ti-MEN-to","Un buon investimento.","Sostantivi"],
["borsa","bolsa de valores","BOR-sa","La borsa sale.","Sostantivi"],
["azione","acción (bursátil)","a-TSJO-ne","Le azioni Apple.","Sostantivi"],
];
